#!/usr/bin/env python

import argparse
from os import listdir, makedirs

ROOT_DIR = "/Users/stephenslatky/dev/classes/"

def main():
    args = get_args()
    class_dir = ROOT_DIR + args.class_name

    folders = listdir(ROOT_DIR)

    if args.class_name not in folders:
        makedirs(class_dir)
    new_assignment(class_dir)


def new_assignment(class_dir):
    folders = listdir(class_dir)
    hw = []
    count = 1
    if folders == []:
        makedirs(class_dir + "/hw1")
    else:
        # Find how many assignemts are already in the folder
        for d in folders:
            if "hw" in d:
                count += 1
    new_ass = "hw" + str(count)
    makedirs(class_dir + "/" + new_ass + "/submission")
    makedirs(class_dir + "/" + new_ass + "/given_material")
    makedirs(class_dir + "/" + new_ass + "/work")
    f =  open(class_dir + "/"+ new_ass + "/README.md" , 'w+')
    f.write("Author: Stephen Slatky\n")


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("class_name", help="Name of class to create directory.")
    return parser.parse_args()


if __name__ == "__main__":
    main()
